"""Tests for the C stubber.

Two layers:
1. Unit tests against pure-Python helpers — always run.
2. Integration tests against ``stub_file`` end-to-end — skipped when libclang
   Python bindings are unavailable. The Docker base image installs
   ``python3-clang-18`` so the integration tests always run in CI.
"""

from __future__ import annotations

import json
import shutil
import tempfile
from pathlib import Path

import pytest

from tools.cstubber.cstubber import (
    DEFAULT_FALLBACK_ARGS,
    DEFAULT_SKIP_DIR_RE,
    STUB_HEADER_CONTENT,
    STUB_INCLUDE_LINE,
    STUB_MARKER,
    StubReport,
    _build_stub_body,
    _ensure_stub_include,
    _find_compound_stmt_offsets,
    _is_already_stubbed,
    _line_col_to_offset,
    load_compile_commands,
    stub_directory,
    stub_file,
    write_stub_header,
)


FIXTURES = Path(__file__).parent / "fixtures"


try:
    import clang.cindex  # type: ignore  # noqa: F401

    LIBCLANG_AVAILABLE = True
except ImportError:
    LIBCLANG_AVAILABLE = False


# ---------------------------------------------------------------------------
# Pure helper tests — no libclang dependency
# ---------------------------------------------------------------------------


def test_line_col_to_offset_basic():
    text = "abc\ndef\nghi"
    assert _line_col_to_offset(text, 1, 1) == 0
    assert _line_col_to_offset(text, 2, 1) == 4
    assert _line_col_to_offset(text, 3, 2) == 9


def test_find_compound_stmt_simple():
    text = "int f(void) {\n    return 0;\n}\n"
    open_b, close_b = _find_compound_stmt_offsets(text, 0)
    assert text[open_b] == "{"
    assert text[close_b] == "}"


def test_find_compound_stmt_knr_style():
    """K&R: parameter type declarations between declarator and body."""
    text = "int legacy(a, b)\nint a;\nint b;\n{\n    return a + b;\n}\n"
    open_b, close_b = _find_compound_stmt_offsets(text, 0)
    assert text[open_b] == "{"
    assert text[close_b] == "}"
    body = text[open_b : close_b + 1]
    assert "return a + b;" in body


def test_find_compound_stmt_skips_string_braces():
    text = 'void f(void) {\n    char *s = "}{";\n    return;\n}\n'
    open_b, close_b = _find_compound_stmt_offsets(text, 0)
    # Closing must be the final brace, not the one inside the string.
    assert close_b == len(text) - 2


def test_find_compound_stmt_skips_char_braces():
    text = "void f(void) {\n    char c = '}';\n    return;\n}\n"
    open_b, close_b = _find_compound_stmt_offsets(text, 0)
    assert close_b == len(text) - 2


def test_find_compound_stmt_skips_block_comment_braces():
    text = "void f(void) {\n    /* } */\n    return;\n}\n"
    open_b, close_b = _find_compound_stmt_offsets(text, 0)
    assert close_b == len(text) - 2


def test_find_compound_stmt_skips_line_comment_braces():
    text = "void f(void) {\n    // }\n    return;\n}\n"
    open_b, close_b = _find_compound_stmt_offsets(text, 0)
    assert close_b == len(text) - 2


def test_find_compound_stmt_handles_nested():
    text = "int g(int n) {\n    if (n) { return 1; }\n    return 0;\n}\n"
    open_b, close_b = _find_compound_stmt_offsets(text, 0)
    assert close_b == len(text) - 2


def test_find_compound_stmt_returns_none_on_unbalanced():
    text = "int f(void) {\n    return 0;\n"
    assert _find_compound_stmt_offsets(text, 0) is None


def test_is_already_stubbed_positive():
    assert _is_already_stubbed("{ STUB_PANIC(\"foo\"); }")


def test_is_already_stubbed_negative():
    assert not _is_already_stubbed("{ return 0; }")


def test_ensure_stub_include_adds_when_missing():
    text = "int main(void) { return 0; }\n"
    new, added = _ensure_stub_include(text)
    assert added
    assert new.startswith(STUB_INCLUDE_LINE)


def test_ensure_stub_include_idempotent():
    text = f"{STUB_INCLUDE_LINE}\nint main(void) {{ return 0; }}\n"
    new, added = _ensure_stub_include(text)
    assert not added
    assert new == text


def test_build_stub_body_shape():
    body = _build_stub_body("parse_json", "    ")
    assert "STUB_PANIC(\"parse_json\");" in body
    assert "/* STUB: generated by cstubber */" in body


def test_load_compile_commands_resolves_relative_includes(tmp_path):
    cc = tmp_path / "compile_commands.json"
    cc.write_text(
        json.dumps(
            [
                {
                    "directory": str(tmp_path / "build"),
                    "command": "gcc -DDEBUG=1 -I../include -Isrc -std=c11 -o foo.o foo.c",
                    "file": "foo.c",
                }
            ]
        )
    )
    db = load_compile_commands(cc)
    flags = list(db.values())[0]
    assert "-DDEBUG=1" in flags
    assert "-std=c11" in flags
    abs_include = str((tmp_path / "include").resolve())
    assert ("-I" + abs_include) in flags


def test_load_compile_commands_handles_arguments_array(tmp_path):
    cc = tmp_path / "compile_commands.json"
    cc.write_text(
        json.dumps(
            [
                {
                    "directory": str(tmp_path),
                    "arguments": ["gcc", "-I.", "-DX=1", "-c", "foo.c"],
                    "file": "foo.c",
                }
            ]
        )
    )
    db = load_compile_commands(cc)
    flags = list(db.values())[0]
    abs_cwd = str(tmp_path.resolve())
    assert ("-I" + abs_cwd) in flags
    assert "-DX=1" in flags


def test_load_compile_commands_missing_file_returns_empty(tmp_path):
    assert load_compile_commands(tmp_path / "nope.json") == {}


def test_load_compile_commands_invalid_json_returns_empty(tmp_path):
    cc = tmp_path / "compile_commands.json"
    cc.write_text("not json")
    assert load_compile_commands(cc) == {}


def test_write_stub_header_idempotent(tmp_path):
    p1 = write_stub_header(tmp_path)
    assert p1.read_text() == STUB_HEADER_CONTENT
    p2 = write_stub_header(tmp_path)
    assert p2 == p1
    assert p2.read_text() == STUB_HEADER_CONTENT


def test_skip_dir_re_matches_common_dirs():
    for d in [
        "/tests/",
        "tests/foo",
        "/examples/",
        "demo/",
        "/third_party/",
        "/vendor/",
        "deps/",
    ]:
        assert DEFAULT_SKIP_DIR_RE.search(d) is not None, d
    for d in ["/src/", "src/foo/", "/lib/", "include/"]:
        assert DEFAULT_SKIP_DIR_RE.search(d) is None, d


# ---------------------------------------------------------------------------
# Integration tests — require libclang
# ---------------------------------------------------------------------------


pytestmark_libclang = pytest.mark.skipif(
    not LIBCLANG_AVAILABLE,
    reason="libclang Python bindings not available — run inside the C base image",
)


def _fixture_pairs():
    inputs = sorted((FIXTURES / "input").glob("*.c"))
    return [(p, FIXTURES / "expected" / p.name) for p in inputs]


@pytestmark_libclang
@pytest.mark.parametrize("input_path,expected_path", _fixture_pairs())
def test_fixture_byte_match(tmp_path, input_path: Path, expected_path: Path):
    """Each fixture's input, after stubbing, must byte-match its expected output."""
    work = tmp_path / "work"
    work.mkdir()
    target = work / input_path.name
    shutil.copy(input_path, target)
    report = stub_directory(work, write_header=True)
    assert (work / "commit0_stub.h").exists()
    assert target.read_text() == expected_path.read_text(), (
        f"\n--- expected ---\n{expected_path.read_text()}\n"
        f"--- got ---\n{target.read_text()}\n--- report ---\n{report.to_dict()}"
    )


@pytestmark_libclang
def test_idempotency(tmp_path):
    """Running cstubber twice on the same file yields identical output."""
    work = tmp_path / "work"
    work.mkdir()
    target = work / "simple.c"
    target.write_text("int add(int a, int b) {\n    return a + b;\n}\n")

    stub_directory(work, write_header=True)
    first = target.read_text()
    header_first = (work / "commit0_stub.h").read_text()

    stub_directory(work, write_header=True)
    second = target.read_text()
    header_second = (work / "commit0_stub.h").read_text()

    assert first == second, "second stub run mutated already-stubbed file"
    assert header_first == header_second
    # No duplicate include line.
    assert second.count(STUB_INCLUDE_LINE) == 1


@pytestmark_libclang
def test_skip_dir_files_untouched(tmp_path):
    work = tmp_path / "work"
    (work / "src").mkdir(parents=True)
    (work / "tests").mkdir(parents=True)
    src_text = "int foo(void) { return 1; }\n"
    test_text = "int test_foo(void) { return 1; }\n"
    (work / "src" / "foo.c").write_text(src_text)
    (work / "tests" / "test_foo.c").write_text(test_text)

    stub_directory(work, write_header=True)

    assert STUB_MARKER in (work / "src" / "foo.c").read_text()
    # tests/ should be untouched.
    assert (work / "tests" / "test_foo.c").read_text() == test_text


@pytestmark_libclang
def test_header_files_never_modified(tmp_path):
    work = tmp_path / "work"
    work.mkdir()
    header_text = "static inline int hot(void) { return 42; }\n"
    (work / "api.h").write_text(header_text)
    stub_directory(work, write_header=True)
    assert (work / "api.h").read_text() == header_text


@pytestmark_libclang
def test_stub_report_counts(tmp_path):
    work = tmp_path / "work"
    work.mkdir()
    (work / "a.c").write_text("int a(void) { return 1; }\nint b(void) { return 2; }\n")
    (work / "b.c").write_text("int c(void) { return 3; }\n")
    report = stub_directory(work, write_header=True)
    assert report.files_processed == 2
    assert report.files_modified == 2
    assert report.functions_stubbed == 3


@pytestmark_libclang
def test_stub_report_serialises():
    r = StubReport()
    r.files_processed = 5
    r.skip("static_in_header", "x")
    d = r.to_dict()
    assert d["files_processed"] == 5
    assert d["functions_skipped"]["static_in_header"] == ["x"]
