#include "commit0_stub.h"
int add(int a, int b) {
    /* STUB: generated by cstubber */
    STUB_PANIC("add");
}

int sub(int a, int b) {
    /* STUB: generated by cstubber */
    STUB_PANIC("sub");
}
