"""Rust-specific patch handling utilities.

Wraps the generic patch generation from utils.py with Rust-specific
filtering: excludes ``target/`` build artifacts and ensures ``Cargo.lock``
is included for reproducibility.
"""

import logging
import re

import git

from commit0.harness.utils import generate_patch_between_commits

logger = logging.getLogger(__name__)


class InvalidRustPatchError(Exception):
    """Raised when a generated Rust patch fails post-filter validation.

    Indicates a regression in :func:`_filter_target_dir` or an upstream change
    to git diff output that lets ``target/`` artefacts through. The raw patch
    text is preserved on the exception so callers can persist it for postmortem.
    """

    def __init__(self, patch: str, message: str = "patch contains target/ artefacts") -> None:
        super().__init__(message)
        self.patch = patch


def generate_rust_patch(
    repo_dir: str,
    base_commit: str,
    target_commit: str,
    *,
    strict: bool = True,
) -> str:
    """Generate a patch between two commits with Rust-specific filtering.

    Calls :func:`generate_patch_between_commits` and post-processes the
    result to strip ``target/`` directory changes while preserving
    ``Cargo.lock`` diffs.

    Parameters
    ----------
    repo_dir : str
        Path to the local git repository.
    base_commit : str
        The old commit hash or reference.
    target_commit : str
        The new commit hash or reference.
    strict : bool, keyword-only, default True
        When True (default), raise :class:`InvalidRustPatchError` if
        post-filter validation detects ``target/`` residue. Pass
        ``strict=False`` to preserve the legacy best-effort behaviour
        (log a warning and return the patch unchanged) — only
        appropriate for reporting artefacts that must never crash the
        caller.

    Returns
    -------
    str
        Filtered patch string.

    Raises
    ------
    InvalidRustPatchError
        When *strict* is True and validation fails. The raw filtered
        patch is preserved on the exception for postmortem inspection.

    """
    repo = git.Repo(repo_dir)
    raw_patch = generate_patch_between_commits(repo, base_commit, target_commit)
    filtered = _filter_target_dir(raw_patch)
    if not validate_rust_patch(filtered):
        msg = (
            f"Rust patch validation failed for repo_dir={repo_dir!r}: "
            "_filter_target_dir let target/ artefacts through. This indicates "
            "a regression in the filter or an upstream change to git diff output."
        )
        if strict:
            raise InvalidRustPatchError(filtered, msg)
        logger.warning("%s (strict=False, returning patch as-is)", msg)
    return filtered


def validate_rust_patch(patch_content: str) -> bool:
    """Validate that a patch does not contain ``target/`` artifacts.

    Checks
    ------
    * No diff headers referencing paths under ``target/``.
    * No binary blob markers from build artifacts inside ``target/``.

    Parameters
    ----------
    patch_content : str
        The unified-diff patch text to validate.

    Returns
    -------
    bool
        ``True`` if the patch is clean, ``False`` otherwise.

    """
    for line in patch_content.splitlines():
        if line.startswith("diff --git") and "/target/" in line:
            return False
        if re.match(r"^(\+\+\+|---)\s+(a|b)/target/", line):
            return False
        if line.startswith("Binary files") and "/target/" in line:
            return False
    return True


def _filter_target_dir(patch: str) -> str:
    """Remove hunks that belong to the ``target/`` directory.

    Splits the patch into per-file sections (delimited by
    ``diff --git ...`` lines) and drops any section whose path falls
    under ``target/``.

    ``Cargo.lock`` is never filtered out.
    """
    if not patch.strip():
        return patch

    sections = re.split(r"(?=^diff --git )", patch, flags=re.MULTILINE)

    kept: list[str] = []
    for section in sections:
        if not section.strip():
            continue
        if _section_is_target(section):
            continue
        kept.append(section)

    return "".join(kept) if kept else "\n\n"


def filter_rust_patch(patch: str, *, strict: bool = True) -> str:
    """Public entry point: strip ``target/`` build artefacts from a raw patch.

    Use this on patches generated by the generic
    :func:`generate_patch_between_commits` so the Rust-specific filtering
    actually runs in the eval path (the dedicated :func:`generate_rust_patch`
    re-opens the repo and is not always on the hot path).

    Parameters
    ----------
    patch : str
        Raw unified-diff text to filter.
    strict : bool, keyword-only, default True
        When True (default), raise :class:`InvalidRustPatchError` if
        the filter fails to strip all ``target/`` residue. Pass
        ``strict=False`` for best-effort reporting artefacts where a
        polluted patch is preferable to a crash.

    Raises
    ------
    InvalidRustPatchError
        When *strict* is True and validation fails after filtering.
    """
    filtered = _filter_target_dir(patch)
    if not validate_rust_patch(filtered):
        msg = (
            "filter_rust_patch: target/ artefacts survived filtering; "
            "this indicates a regression in _filter_target_dir or an "
            "upstream change to git diff output."
        )
        if strict:
            raise InvalidRustPatchError(filtered, msg)
        logger.warning("%s (strict=False, returning patch as-is)", msg)
    return filtered


# A diff path is a build-artefact path if a `target/` directory component sits
# at a crate root: `a/target/...` (top-level) or `a/<member>/target/...`
# (workspace member). Matches the substring intent of validate_rust_patch
# while still requiring `target` to be a full path component (so a source file
# like `a/src/target_helpers.rs` is NOT stripped).
# N23: `[^\s]+` bans whitespace, so a legitimate workspace member path with a
# space (rust cargo names allow it) would fail to match the target check and
# any target/ under such a member would leak through the filter. `[^/]+` is
# strict-per-path-component (still excludes / to prevent match escape) but
# tolerates spaces the same way git does.
_TARGET_PATH_RE = re.compile(r"[ab]/(?:[^/]+/)?target/")


def _section_is_target(section: str) -> bool:
    """Return True if *section* modifies a path under any ``target/`` dir."""
    first_line = section.split("\n", 1)[0]
    if not first_line.startswith("diff --git"):
        return False
    # "diff --git a/<path> b/<path>" — check both a/ and b/ paths, including
    # nested workspace-member target dirs (consistent with validate_rust_patch).
    return bool(_TARGET_PATH_RE.search(first_line))
